# Generated by Django 4.2.5 on 2023-10-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='temp',
            field=models.CharField(choices=[('hot', 'hot'), ('ice', 'ice')], default='hot', max_length=3),
        ),
    ]
